### ISSUE TITLE
Cannot install https://github.com/liveryvideo/livery-sdk-ios-spm package

### ISSUE THREAD

**Issue by dk-jlew** [liveryvideo/livery-sdk-ios-spm#1]
The package appears to have a binary XCFramework dependency which is failing to download:

`failed downloading 'https://sdk-ios-binaries.liveryvideo.com/xcframework/Livery-1.3.2.zip' which is required by binary target 'Livery': badResponseStatusCode(401)`

When I visit this URL in a browser, I am prompted for basic authentication credentials.

**Comment by santanaNogueira** [comment]
To use the package you have to be a Livery Video client. In that case, you will have credentials to successfully download it. The credentials should be added to your `~/.netrc` file as described on the README.
